<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="himaleshnalam" ignored="0" name="Test" tests="2" failures="2" timestamp="2020-02-14T13:54:16 IST" time="0.119" errors="0">
  <testcase name="Test1" time="0.023" classname="com.TestNGConcepts.TestRetry">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.TestNGConcepts.TestRetry.Test1(TestRetry.java:13)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.004" classname="com.TestNGConcepts.TestRetry">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.TestNGConcepts.TestRetry.Test2(TestRetry.java:19)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- Test -->
